
name: Bank Frontend Pipeline

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build Docker image
      run: docker build -t bank-app-frontend:latest .

    - name: Authenticate Docker to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin 381492269344.dkr.ecr.us-east-1.amazonaws.com

    - name: Tag and push Docker image
      run: |
        docker tag bank-app-frontend:latest 381492269344.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}
        docker push 381492269344.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }}

    - name: Clean up local Docker images
      run: |
        docker rmi bank-app-frontend:latest || true
        docker rmi 381492269344.dkr.ecr.us-east-1.amazonaws.com/bank-frontend:${{ github.run_number }} || true
